### ISSUE TITLE
Support reading the current version from a helm Chart.yaml

### ISSUE THREAD

**Issue by garethjevans** [jenkinsci/conventional-commits-plugin#20]
### Feature Request

May need to support version & appVersion

**Comment by philippart-s** [comment]
@ADI10HERO feel free to assign to me this issue 😉

**Comment by ADI10HERO** [comment]
Thank you for contributing @philippart-s 😄

**Comment by philippart-s** [comment]
I think there is two ways to do this : use the helm command _show chart_ or use Jackson to read the YAML file.
The Helm command output is for example : 
```bash
$ helm show chart .
apiVersion: v2
appVersion: 0.0.1
description: xxxx
home: https://github.com/xxx
maintainers:
- name: xxxx
name: xxx
sources:
- https://github.com/xxx
version: 0.0.36
```
I think there is no gain to use the command : we'll need to parse the output and depend of the Helm command configuration in the path, the loading of the YAML in a map with Jackson seem more easiest and need no Helm installation configured.

About your interrogation @garethjevans _May need to support version & appVersion_ : I am not sure it's a good idea because the _appVersion_ is optional and open for the format (not necessary Semver) as the documentation explain : https://helm.sh/docs/topics/charts/#the-chartyaml-file
